#!/bin/bash

# Kill any old session
tmux kill-session -t arkadia 2> /dev/null

# Start new tmux session and set the panes
tmux new-session -d -s arkadia 'tintin -G run.tin'
tmux splitw -h -t arkadia -p 50 'tintin -G conf/conf_status'

# Attach to the session
tmux selectp -t 0
tmux attach-session -t arkadia
